### ISSUE TITLE
Add reusable sections to boilerplate

### ISSUE THREAD

**Issue by weotch** [BKWLD/create-cloak-app#21]
See P&B

- [x] Add actual reusable section component
- [x] Add queries

**Comment by weotch** [comment]
@mattaebersold, oh reusable section master, is P&B still the best project to pull an example of reusable section modeling from?  Or were there improvements made at some point?

**Comment by mattaebersold** [comment]
@weotch COR uses it too, and I think both are clean. 
- blocks.gql has the wrapperBlocks and nonWrapperBlocks fragments
- list.vue does the recursive blocks
- I remember there being some fuss with the index set on the first couple of blocks to load immediately? Like above the fold stuff. I remember that the indexes were getting re-set to 1 I think for child blocks within a reusable section?
- set up in Craft

**Comment by weotch** [comment]
Will ship with #70
