### ISSUE TITLE
Add Default SEO Fields to Craft CMS

### ISSUE THREAD

**Issue by sjstark** [BKWLD/create-cloak-app#40]
Seems as though there's four fields we will always use with SEO in Craft (`metaTitle`, `metaDescription`, `metaImage`, and `robots`). Should we default add these to Craft and implement support for them since we have support for them on the front end as well?

**Comment by sjstark** [comment]
Realized we swapped to using Super tables for `SEO`

**Comment by weotch** [comment]
I've been pretty torn about which way to model SEO TBH.  Let me know if Super Tables gives you any grief.
