### ISSUE TITLE
Outdated stylus conventions

### ISSUE THREAD

**Issue by sjstark** [BKWLD/create-cloak-app#79]
![Screen Shot 2022-08-09 at 9 58 35 AM](https://user-images.githubusercontent.com/6759557/183709280-5f0ffae3-163e-4633-8614-b1c99b615c44.png)

It seems like we're using dated combinators somewhere within the package, which is leading to functionality not working perfectly (Can't seem to get layout mixins to work like `+tablet-up()`)

**Comment by weotch** [comment]
I updated vue-ssr-carousel with a fix for this https://github.com/BKWLD/vue-ssr-carousel/pull/79.  I'm not sure where else it's needed.  I don't see either `>>>` or `/deep/` in _this_ package or in https://github.com/BKWLD/stylus-library.  If you run across any instances in one of our packages, lemme know.

I wouldn't _expect_ the breakpoint mixins to be affected by this...

**Comment by weotch** [comment]
Found another case: https://github.com/BKWLD/cloak-visual/pull/10

**Comment by weotch** [comment]
I think that was the last one, can no longer repro those warnings on https://github.com/BKWLD/bukwild.com
